name: Build-Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 17
          distribution: oracle

      - name: Compile
        run: mvn compile -Drevision=1.${{ github.run_number }}.0

      - name: SN Register Artifact
        uses: ServiceNow/servicenow-devops-register-artifact@v5.1.0
        with:
          devops-integration-token: ${{ secrets.SN_TOKEN }}
          instance-url: ${{ secrets.SN_URL }}
          tool-id: ${{ secrets.SN_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: ${{ github.job }}
          artifacts: '[{"name": "demo-solutions1-gha", "version": "1.${{ github.run_number }}.0", "repositoryName": "${{ github.repository }}"}]'
  
  test:
    needs: build 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 17
          distribution: oracle

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: | 
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Drevision=1.${{ github.run_number }}.0
    
      - name: ServiceNow DevOps Unit Test Results
        uses: ServiceNow/servicenow-devops-test-report@v5.1.0
        with:
          instance-url: ${{ secrets.SN_URL }}
          devops-integration-token: ${{ secrets.SN_TOKEN }}
          tool-id: ${{ secrets.SN_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: ${{ github.job }}
          xml-report-filename: target/surefire-reports/TEST-com.rapdev.maths.MathsTest.xml
      
      - name: ServiceNow DevOps Sonar
        uses: ServiceNow/servicenow-devops-sonar@v5.1.0
        with:
          instance-url: ${{ secrets.SN_URL }}
          devops-integration-token: ${{ secrets.SN_TOKEN }}
          tool-id: ${{ secrets.SN_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: ${{ github.job }}
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
          sonar-project-key: rapdev-io_solutions-1-gha

  package-registration:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: SN Register Package
        uses: ServiceNow/servicenow-devops-register-package@v5.1.0
        with:
          devops-integration-token: ${{ secrets.SN_TOKEN }}
          instance-url: ${{ secrets.SN_URL }}
          tool-id: ${{ secrets.SN_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: ${{ github.job }}
          artifacts: '[{"name": "demo-solutions1-gha", "version": "1.${{ github.run_number }}.0", "repositoryName": "${{ github.repository }}"}]'
          package-name: 'demo-solutions1-package - ${{ github.run_number }}'
          
      - name: ServiceNow DevOps Change Automation
        uses: ServiceNow/servicenow-devops-change@v5.1.0
        with:
          instance-url: ${{ secrets.SN_URL }}
          devops-integration-token: ${{ secrets.SN_TOKEN }}
          tool-id: ${{ secrets.SN_TOOL_ID }}
          job-name: ${{ github.job }}
          context-github: ${{ toJSON(github) }}
          change-request: '{}'
          deployment-gate: '{"environment":"Production","jobName":"deploy"}'

  deploy:
    needs: package-registration
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Run a one-line script
        run: echo Deploying Application...
